-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.auth_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL UNIQUE CHECK (email::text <> ''::text),
  password_hash character varying NOT NULL,
  first_name character varying,
  last_name character varying,
  phone character varying NOT NULL,
  role character varying NOT NULL DEFAULT 'owner'::character varying CHECK (role::text = ANY (ARRAY['owner'::character varying::text, 'clinic'::character varying::text])),
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT auth_users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pet_owners (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  full_name character varying NOT NULL,
  email character varying NOT NULL,
  phone character varying NOT NULL,
  address text,
  state character varying,
  zip_code character varying,
  country character varying,
  profile_image_url character varying,
  bio text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  latitude double precision,
  longitude double precision,
  CONSTRAINT pet_owners_pkey PRIMARY KEY (id),
  CONSTRAINT pet_owners_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.auth_users(id)
);
CREATE TABLE public.clinics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  clinic_name character varying NOT NULL,
  email character varying NOT NULL,
  phone character varying,
  address text NOT NULL,
  city character varying,
  state character varying,
  zip_code character varying,
  country character varying,
  clinic_logo_url character varying,
  registration_number character varying,
  license_number character varying,
  website character varying,
  opening_hours character varying,
  description text,
  is_verified boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  license_document_url character varying,
  latitude double precision,
  longitude double precision,
  CONSTRAINT clinics_pkey PRIMARY KEY (id),
  CONSTRAINT clinics_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.auth_users(id)
);
CREATE TABLE public.pets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name character varying NOT NULL,
  type character varying NOT NULL,
  breed character varying NOT NULL,
  gender character varying,
  date_of_birth date NOT NULL,
  weight numeric,
  weight_unit character varying DEFAULT 'kg'::character varying,
  blood_type character varying,
  color_markings text,
  allergies text,
  medical_conditions text,
  microchip_id character varying,
  profile_image_url character varying,
  notes text,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pets_pkey PRIMARY KEY (id),
  CONSTRAINT pets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.pet_owners(user_id)
);
CREATE TABLE public.vaccine_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pet_id uuid NOT NULL,
  file_name character varying NOT NULL,
  file_url character varying NOT NULL,
  file_type character varying,
  file_size bigint,
  upload_date date NOT NULL,
  description text,
  uploaded_by uuid,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT vaccine_records_pkey PRIMARY KEY (id),
  CONSTRAINT vaccine_records_pet_id_fkey FOREIGN KEY (pet_id) REFERENCES public.pets(id),
  CONSTRAINT vaccine_records_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.auth_users(id)
);
CREATE TABLE public.medical_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pet_id uuid NOT NULL,
  clinic_id uuid,
  record_type character varying,
  visit_date date,
  diagnosis text,
  treatment text,
  notes text,
  next_visit_date date,
  veterinarian_name character varying,
  file_url character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT medical_records_pkey PRIMARY KEY (id),
  CONSTRAINT medical_records_pet_id_fkey FOREIGN KEY (pet_id) REFERENCES public.pets(id),
  CONSTRAINT medical_records_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.appointments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pet_id uuid NOT NULL,
  clinic_id uuid NOT NULL,
  owner_id uuid NOT NULL,
  appointment_date date NOT NULL,
  appointment_time time without time zone NOT NULL,
  reason character varying,
  status character varying DEFAULT 'scheduled'::character varying,
  notes text,
  reminder_sent boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT appointments_pkey PRIMARY KEY (id),
  CONSTRAINT appointments_pet_id_fkey FOREIGN KEY (pet_id) REFERENCES public.pets(id),
  CONSTRAINT appointments_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT appointments_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.pet_owners(user_id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  user_role character varying CHECK (user_role IS NULL OR (user_role::text = ANY (ARRAY['owner'::character varying::text, 'clinic'::character varying::text, 'admin'::character varying::text]))),
  type character varying NOT NULL,
  title character varying NOT NULL,
  message text NOT NULL,
  entity_type character varying,
  entity_id uuid,
  link_url character varying,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.auth_users(id)
);
CREATE TABLE public.clinic_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  appointment_id uuid NOT NULL UNIQUE,
  clinic_id uuid NOT NULL,
  pet_id uuid NOT NULL,
  owner_id uuid NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  treatment character varying NOT NULL,
  comment text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT clinic_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT clinic_reviews_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT clinic_reviews_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT clinic_reviews_pet_id_fkey FOREIGN KEY (pet_id) REFERENCES public.pets(id),
  CONSTRAINT clinic_reviews_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.pet_owners(user_id)
);